### ISSUE TITLE
Fix WS initial connection issues

### ISSUE THREAD

**Issue by skeet70** [Duelers/Duelers#184]
```console
Feb 29, 2020 11:17:05 PM org.glassfish.tyrus.server.ServerContainerFactory create
INFO: Provider class loaded: org.glassfish.tyrus.container.grizzly.GrizzlyEngine
Feb 29, 2020 11:17:07 PM org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [0.0.0.0:8888]
Feb 29, 2020 11:17:07 PM org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer] Started.
Feb 29, 2020 11:17:07 PM org.glassfish.tyrus.server.Server start
INFO: WebSocket Registered apps: URLs all start with ws://localhost:8888
Feb 29, 2020 11:17:07 PM org.glassfish.tyrus.server.Server start
INFO: WebSocket server started.
Please press a key to stop the server.Exception in thread "Thread-9" java.lang.RuntimeException: com.neovisionaries.ws.client.OpeningHandshakeException: The status code of the opening handshake response is not '101 Switching Protocols'. The status line is: HTTP/1.1 404 Not Found
at controller.Client.connect(Client.java:75)
at controller.Client.lambda$makeConnection$9(Client.java:289)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.neovisionaries.ws.client.OpeningHandshakeException: The status code of the opening handshake response is not '101 Switching Protocols'. The status line is: HTTP/1.1 404 Not Found
at com.neovisionaries.ws.client.HandshakeReader.validateStatusLine(HandshakeReader.java:232)
at com.neovisionaries.ws.client.HandshakeReader.readHandshake(HandshakeReader.java:54)
at com.neovisionaries.ws.client.WebSocket.readHandshake(WebSocket.java:3412)
at com.neovisionaries.ws.client.WebSocket.shakeHands(WebSocket.java:3291)
at com.neovisionaries.ws.client.WebSocket.connect(WebSocket.java:2326)
at controller.Client.connect(Client.java:73)
... 2 more
```

**Comment by skeet70** [comment]
@MaSer713 if this is already done link the PR to it and close it, I couldn't find one quickly searching.
